[package]
name = "citeproc"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["std"] }
human_name = "2.0.2"
isocountry = "0.3.2"
itertools = "0.11.0"
rowan = "0.15.11"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
titlecase = "2.2.1"
unicode-normalization = "0.1.22"
url = "=2.3.1"

[lib]
doctest = false

[dev-dependencies]
expect-test = "1.4.1"
parser = { path = "../parser" }
