[package]
name = "texlab"
description = "LaTeX Language Server"
version = "4.3.2"
license = "GPL-3.0"
readme = "README.md"
authors = [
  "Eric Förster <eric.foerster@outlook.com>",
  "Patrick Förster <patrick.foerster@outlook.de>",
]
edition = "2021"
rust-version = "1.60"
homepage = "https://github.com/latex-lsp/texlab"
repository = "https://github.com/latex-lsp/texlab"
documentation = "https://github.com/latex-lsp/texlab"
keywords = ["lsp", "server", "latex", "bibtex"]
categories = ["development-tools"]
exclude = [
  ".gitattributes",
  ".gitignore",
  ".github/**",
  "tests/it/**",
  "*.snap",
  "texlab.1",
  "texlab.pdf",
  "texlab.tex",
]

[[bin]]
name = "texlab"
test = false

[lib]
doctest = false

[dependencies]
anyhow = "1.0.66"
byteorder = "1.4.3"
chrono = { version = "0.4.23", default-features = false, features = ["std"] }
clap = { version = "4.0.29", features = ["derive"] }
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
dirs = "4.0.0"
encoding_rs = "0.8.31"
encoding_rs_io = "0.1.7"
fern = "0.6.1"
flate2 = "1.0.25"
flume = "0.10.14"
fuzzy-matcher = { version = "0.3.7", features = ["compact"] }
human_name = { version = "2.0.1", default-features = false }
isocountry = "0.3.2"
itertools = "0.10.5"
log = "0.4.17"
logos = "0.12.1"
lsp-server = "0.6.0"
lsp-types = { version = "0.93.2", features = ["proposed"] }
notify = "5.0.0"
once_cell = "1.16.0"
regex = "1.7.0"
rowan = "0.15.10"
rustc-hash = "1.1.0"
serde = "1.0.151"
serde_json = "1.0.90"
serde_millis = "0.1.1"
serde_regex = "1.1.0"
serde_repr = "0.1.10"
smol_str = { version = "0.1.23", features = ["serde"] }
strum = { version = "0.24.1", features = ["derive"] }
tempfile = "3.3.0"
thiserror = "1.0.38"
threadpool = "1.8.1"
titlecase = "2.2.1"
unicode-normalization = "0.1.22"
url = { version = "2.3.1", features = ["serde"] }

[dependencies.salsa]
git = "https://github.com/salsa-rs/salsa"
rev = "252d21e358979cd684666ebc32d2bc49d6f1d3f0"
package = "salsa-2022"

[dev-dependencies]
assert_unordered = "0.3.5"
criterion = { version = "0.4.0" }
env_logger = "0.10.0"
insta = { version = "1.23.0", features = ["glob", "redactions", "json"] }
jod-thread = "0.1.2"

[profile.release]
lto = "thin"
incremental = true

[profile.bench]
lto = "thin"

[[bench]]
name = "bench_main"
path = "benches/bench_main.rs"
harness = false
