[workspace]
members = ["crates/*"]

[workspace.package]
license = "GPL-3.0"
authors = [
    "Eric Förster <eric.foerster@outlook.com>",
    "Patrick Förster <patrick.foerster@outlook.de>",
]
edition = "2021"
rust-version = "1.65"

[profile.release]
lto = "thin"
incremental = true

[profile.bench]
lto = "thin"
incremental = true
