[package]
name = "base-feature"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rustc-hash = "1.1.0"
url = "2.3.1"

[lib]
doctest = false
