[package]
name = "parser"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logos = "0.13.0"
once_cell = "1.17.1"
regex = "1.7.3"
rowan = "0.15.11"
syntax = { path = "../syntax" }

[dev-dependencies]
insta = { version = "1.29.0", features = ["glob", "redactions", "json"] }

[lib]
doctest = false
