[package]
name = "commands"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.70"
base-db = { path = "../base-db" }
base-feature = { path = "../base-feature" }
itertools = "0.10.5"
log = "0.4.17"
rowan = "0.15.11"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
thiserror = "1.0.40"
url = "2.3.1"

[lib]
doctest = false
