[package]
name = "texlab"
description = "LaTeX Language Server"
version = "5.5.1"
license.workspace = true
readme = "README.md"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage = "https://github.com/latex-lsp/texlab"
repository = "https://github.com/latex-lsp/texlab"
documentation = "https://github.com/latex-lsp/texlab"
keywords = ["lsp", "server", "latex", "bibtex"]
categories = ["development-tools"]
exclude = [
  ".gitattributes",
  ".gitignore",
  ".github/**",
  "tests/it/**",
  "*.snap",
  "texlab.1",
  "texlab.pdf",
  "texlab.tex",
]

[[bin]]
name = "texlab"
test = false

[lib]
doctest = false

[dependencies]
anyhow = "1.0.70"
base-db = { path = "../base-db" }
citeproc = { path = "../citeproc" }
clap = { version = "4.2.2", features = ["derive"] }
commands = { path = "../commands" }
crossbeam-channel = "0.5.8"
dirs = "5.0.0"
distro = { path = "../distro" }
encoding_rs = "0.8.32"
encoding_rs_io = "0.1.7"
fern = "0.6.2"
flate2 = "1.0.25"
fuzzy-matcher = { version = "0.3.7", features = ["compact"] }
itertools = "0.10.5"
log = "0.4.17"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
notify = "5.1.0"
once_cell = "1.17.1"
parking_lot = "0.12.1"
parser = { path = "../parser" }
regex = "1.7.3"
rowan = "0.15.11"
rustc-hash = "1.1.0"
serde = "1.0.160"
serde_json = "1.0.96"
serde_regex = "1.1.0"
serde_repr = "0.1.12"
smol_str = { version = "0.2.0", features = ["serde"] }
syntax = { path = "../syntax" }
tempfile = "3.5.0"
threadpool = "1.8.1"
titlecase = "2.2.1"
symbols = { path = "../symbols" }

[dev-dependencies]
assert_unordered = "0.3.5"
criterion = { version = "0.4.0" }
insta = { version = "1.28.0", features = ["glob", "redactions", "json"] }

[[bench]]
name = "bench_main"
path = "benches/bench_main.rs"
harness = false
