[package]
name = "base-db"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
distro = { path = "../distro" }
log = "0.4.17"
notify = "5.1.0"
parser = { path = "../parser" }
regex = "1.7.3"
rowan = "0.15.11"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
text-size = "1.1.0"
url = "2.3.1"

[lib]
doctest = false
