name: CI
on:
  pull_request:
  push:
    branches:
      - master
env:
  CARGO_INCREMENTAL: 0
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10
jobs:
  build:
    name: Build (${{ matrix.target }}, ${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            run-tests: true
            use-cross: false
            toolchain: stable
          - os: windows-latest
            target: i686-pc-windows-msvc
            run-tests: false
            use-cross: false
            toolchain: stable
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            run-tests: false
            use-cross: false
            toolchain: stable

          - os: macos-latest
            target: x86_64-apple-darwin
            run-tests: true
            use-cross: false
            toolchain: stable
          - os: macos-latest
            target: aarch64-apple-darwin
            run-tests: false
            use-cross: false
            toolchain: stable

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            run-tests: true
            use-cross: false
            toolchain: 1.58.1
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            run-tests: false
            use-cross: true
            toolchain: stable
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            run-tests: false
            use-cross: true
            toolchain: stable
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            run-tests: false
            use-cross: false
            toolchain: stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }} --all-features --no-run --locked
          use-cross: ${{ matrix.use-cross }}
      - uses: actions-rs/cargo@v1
        if: ${{ matrix.run-tests }}
        with:
          command: test
          args: --target ${{ matrix.target }} --all-features -- --nocapture --quiet
          use-cross: ${{ matrix.use-cross }}
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v1
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
